operators:
- github: philote-dev
  slack_user_id: U0BA7EHAKJR
  rotation_order: 0
  enabled: true
- github: meric233
  slack_user_id: U0BAARXNKC2
  rotation_order: 1
  enabled: true
- github: alsy7009
  slack_user_id: U0B9K2XTTBL
  rotation_order: 2
  enabled: true
